# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainView.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from gui.openFileDialog import OpenFileDialog
from operation.FileLoader import FileLoader
from data.PandasModel import PandasModel
from data.DataFrame import DataFrame

class Ui_MainWindow(object):

    def __init__(self):
        self.data_frame = DataFrame()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 631, 541))
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_data = QtWidgets.QAction(MainWindow)
        self.actionLoad_data.setObjectName("actionLoad_data")
        self.menuFile.addAction(self.actionLoad_data)
        self.menubar.addAction(self.menuFile.menuAction())

        self.actionLoad_data.triggered.connect(lambda: self.openDialog())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "Plik"))
        self.actionLoad_data.setText(_translate("MainWindow", "Wczytaj dane"))

        

    def openDialog(self):
        print("ASADDADADD")
        self.open_file_dialog = QtWidgets.QDialog()
        self.ui = OpenFileDialog()
        self.ui.setupUi(self.open_file_dialog)
        self.open_file_dialog.show()
        self.ui.filePathInput.text()
        self.ui.okButton.clicked.connect(lambda: self.open_file())
        self.ui.cancelButton.clicked.connect(lambda: self.close_file_dialog())

    def open_file(self):
        file_path = self.ui.filePathInput.text()
        separator = ''
        if self.ui.tabRadio.isChecked():
            separator = '\t'
        elif self.ui.spaceRadio.isChecked():
            separator = ' '
        elif self.ui.commaRadio.isChecked():
            separator = ','
        elif self.ui.semicolonRadio.isChecked():
            separator = ';'

        is_headers = self.ui.checkBoxHeaders.isChecked()
        print(separator)
        print(is_headers)
        col_index = False
        if is_headers:
            col_index = 0
        file_loader: FileLoader = FileLoader()
        self.data_frame.df = file_loader.loadFile(file_path, separator, col_index)
        self.setup_table(self.data_frame)
        print(self.data_frame.df.columns)
        self.close_file_dialog()

    def close_file_dialog(self):
        self.open_file_dialog.close()

    def setup_table(self, df):
        self.pandas_model: PandasModel = PandasModel(df)
        self.tableView.setModel(self.pandas_model)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
