# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2DPlot.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Plot2DDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.comboBoxColumnX = QtWidgets.QComboBox(Dialog)
        self.comboBoxColumnX.setGeometry(QtCore.QRect(80, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxColumnX.setFont(font)
        self.comboBoxColumnX.setObjectName("comboBoxColumnX")
        self.comboBoxColumnY = QtWidgets.QComboBox(Dialog)
        self.comboBoxColumnY.setGeometry(QtCore.QRect(80, 80, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxColumnY.setFont(font)
        self.comboBoxColumnY.setObjectName("comboBoxColumnY")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 20, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(170, 220, 71, 31))
        self.okButton.setObjectName("okButton")
        self.checkBoxColors = QtWidgets.QCheckBox(Dialog)
        self.checkBoxColors.setGeometry(QtCore.QRect(80, 150, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBoxColors.setFont(font)
        self.checkBoxColors.setObjectName("checkBoxColors")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "X"))
        self.label_2.setText(_translate("Dialog", "Y"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.checkBoxColors.setText(_translate("Dialog", "Zastosuj kolory do klas"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
